###Get all users
GET http://localhost:3000/users 
Authorization: bearer -admin token here-

### POST new user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Jeremy",
    "lastName": "Mathew Johnson",
    "password": "1234MM",
    "age": 30
}


### login in API
POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "name": "Jeremy",
    "lastName": "Mathew Johnson",
    "password": "1234MM"
}




